gambot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  left_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_rim_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  back_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_rim_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: right_rim_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}